EWPP-4991: Update PHP versions.
openeuropa/task-runner-drupal-project-symlink pull request #15
Opened 2024-12-13 07:24 UTC by drishu

2024-12-13 12:12 UTC, sergepavle submitted a review, later dismissed

2024-12-13 13:13 UTC, nagyad requested changes

2024-12-13 13:13 UTC, nagyad commented on .drone.yml
> +    - 8.2
I think we could skip 8.2, it's not really relevant if we have 8.1 and 8.3.

2024-12-16 11:03 UTC, nagyad requested changes

2024-12-16 11:03 UTC, nagyad commented on docker-compose.yml
>  version: '2'
This value is obsolete we should remove it in all components.

2024-12-16 12:04 UTC, nagyad approved these changes

2024-12-16 12:08 UTC, sergepavle approved these changes

2024-12-16 12:18 UTC, merged